# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  rawvsotelpocapi:
    image: rawvsotelpocapi
    build:
      context: .
      dockerfile: src/Dockerfile
    ports:
      - 7130:7130
    environment:
      - ASPNETCORE_URLS=http://*:7130
  postgres:
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
  zipkin:
    image: openzipkin/zipkin
    ports:
      - 9411:9411
  jaeger:
    image: jaegertracing/all-in-one:1.31
    ports: # not everything is needed, but idc
      - 5775:5775/udp # legacy zipkin.thrift agent
      - 6831:6831/udp # compact jaeger.thrift agent  <--- using it
      - 6832:6832/udp # binary jaeger.thrift agent
      - 5778:5778     # serve configs
      - 16686:16686   # serve frontend
      - 14250:14250   # direct model.proto colletor
      - 14268:14268   # direct jaeger.thrift collector  
      - 14269:14269   # admin port: health check at / and metrics at /metrics
      - 9412:9411     # zipkin compatible collector
  tempo:
    image: grafana/tempo:latest
    command: [ "-config.file=/etc/tempo.yaml" ]
    volumes:
      - ./tempo-local.yaml:/etc/tempo.yaml
      - ./tempo-data:/tmp/tempo
    ports:
      - 3200:3200  # tempo
      - 4317:4317  # otlp grpc collector  <--- using it
      - 4318:4318  # otlp http collector
      - 9413:9411  # zipkin compatible collector
      - 14270:14268 # jaeger compatible collector
  grafana:
    image: grafana/grafana:8.1.6
    volumes:
      - ./grafana-datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
    ports:
      - "3000:3000" # serve frontend
  prometheus:
    image: prom/prometheus
    ports:
      - 9090:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
# OTEL collector pipeline can convert between varius trace formats (same as Jaeger agent)
#  otel-collector:
#    image: otel/opentelemetry-collector:0.32.0
#    command: [ "--config=/etc/otel-collector.yaml" ]
#    volumes:
#      - ./otel-collector.yaml:/etc/otel-collector.yaml